### ISSUE TITLE
NoSuchFileException when a translation memory is deleted

### ISSUE THREAD

**Issue by AlexSmarandache15** [rmraya/Fluenta#5]
Hello,

We are currently building an Oxygen XML Editor plugin that integrates Fluenta into the DITA Maps Manager. 

Usually when we delete a memory that is not associated with a project, an exception is thrown in the console.
I noticed that although this exception appears, the memory is deleted from the database and when the application is restarted, it will no longer appear.
Do you think it would be safe to ignore this exception? (if the memory is deleted from the database, it seems to work). Or are there other causes and in fact the process was not complete?

This problem is also reproduced with Fluenta version 2.5.0. The reproduction steps are as follows:
1) Create a new memory
2) Remove the created memory

I put here the exception thrown in the console:
java.nio.file.NoSuchFileException: C:\Users\alex_smarandache\AppData\Roaming\Fluenta\TMEngines\1664956425828
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at com.maxprograms.fluenta.controllers.LocalController.deltree(Unknown Source)
        at com.maxprograms.fluenta.controllers.LocalController.removeMemory(Unknown Source)
        at com.maxprograms.fluenta.views.MemoriesView.removeMemory(Unknown Source)
        at com.maxprograms.fluenta.views.MemoriesView$5.mouseDown(Unknown Source)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
        at com.maxprograms.fluenta.MainView.show(Unknown Source)
        at com.maxprograms.fluenta.Fluenta.main(Unknown Source)

**Comment by rmraya** [comment]
This has already changed in current private branch fro Fluenta 3.0

**Comment by rmraya** [comment]
BTW, you can safely ignore the message.
